Automates announcement banner removal
cfpb/hmda-frontend pull request #1641
Opened 2022-11-03 19:23 UTC by Michaeldremy

Closes #1610

2022-11-04 16:48 UTC, meissadia requested changes

2022-11-04 18:00 UTC, Michaeldremy commented on src/homepage/AnnouncementBanner.jsx
> +          item.props.endDate >= currentDate.toLocaleDateString()
Code has been updated by removing unnecessary `useEffect` code. Only changes to this branch as of last commit are related to adding `endDate` to the configs if that banner has a `endDate`.

2022-11-04 18:02 UTC, Michaeldremy reviewed
Code has been updated to reflect code review comment.

2022-11-10 00:29 UTC, meissadia approved these changes
I think this gives each banner a nice long life.

2022-11-17 19:07 UTC, chynnakeys commented
I think these dates work for me @meissadia @Michaeldremy

2022-11-17 19:47 UTC, merged